UPDATE email_sequences
SET
  name = 'VantoOS Executive Beta — 11 Days / 11 Pages',
  steps = steps::jsonb || '[
    {"type":"wait","duration_hours":24},
    {"type":"send_email","from_name":"VantoOS Team","subject":"Day 11: Become Your Own CFO — Budgets, Bank Imports & AI Finance Mentor 📊","content":"<p style=\"background:#f0f0ff;border-left:4px solid #6366f1;padding:12px 16px;margin-bottom:20px;font-size:13px;color:#334155;line-height:1.6;\"><strong>🟣 VantoOS Executive Beta</strong><br/>You''re part of a private 20-person cohort testing an executive system built for South African leaders. Each day you''ll explore one page and complete one 10-minute task. Your feedback will directly shape the product.</p><p>Hi {{first_name}},</p><p>On Day 5 you got a taste of VantoOS Finance. Today we go deeper — into the tools that turn you into your own CFO.</p><p>👉 <a href=\"https://executive.onlinecourseformlm.com/finance\">https://executive.onlinecourseformlm.com/finance</a></p><p><strong>THREE POWER FEATURES TO EXPLORE TODAY:</strong></p><p><strong>1️⃣ BUDGET COMMAND CENTRE</strong></p><ul><li>Click the \"Budget\" tab</li><li>Add a recurring bill (rent, internet, insurance — anything you pay regularly)</li><li>Set the cadence (monthly, yearly, or custom) and the due day</li><li>VantoOS will auto-generate payment events AND warn you 7 days before each one is due</li><li>Toggle \"Autopay\" on items that debit automatically so you know what''s manual vs automatic</li></ul><p><strong>2️⃣ BANK STATEMENT IMPORT</strong></p><ul><li>Click the \"Bank Import\" tab</li><li>Upload a CSV bank statement from your bank</li><li>VantoOS will parse every transaction, detect merchants, and auto-categorise them (groceries, transport, subscriptions, etc.)</li><li>You can create custom merchant rules so future imports categorise perfectly</li></ul><p><strong>3️⃣ AI FINANCE MENTOR</strong></p><ul><li>Click the 🤖 icon in the Finance section</li><li>Ask questions like:<ul><li>\"Where am I overspending?\"</li><li>\"Can I afford to hire someone next month?\"</li><li>\"What''s my savings rate?\"</li></ul></li><li>The mentor analyses YOUR actual data — income streams, expenses, debts, and budget — to give personalised advice</li></ul><p>💡 <strong>TIP:</strong> Log your debts too (Finance → Debts). The AI Mentor factors them into its advice, giving you a complete financial picture.</p><p><strong>Tomorrow:</strong> Managing government tenders like a pro with TenderOS.</p><p>The VantoOS Team</p>"}
  ]'::jsonb,
  updated_at = now()
WHERE id = '0f23eef6-6c16-4f9f-9357-8a67e358abe2';
